BOOKS_DATA_FILEPATH = 'data/db_data/Books.csv'
RATINGS_DATA_FILEPATH = 'data/db_data/Ratings.csv'
PIVOT_TABLE_FILEPATH = 'artifacts/pivot_table.pkl'
SIMILARITY_SCORES_FILEPATH = 'artifacts/similarity_scores.pkl'
BOOKS_POPULARITY_DATA_FILEPATH = 'artifacts/data/popularity_based_df.csv'